### ISSUE TITLE
Student

### ISSUE THREAD

**Issue by jsncbt** [DCUBEDcode/headway#4]
# **What is a Student?**
A Student is invited to the system by an Admin. A Student is ultimately assigned one or more Courses #3 which they must then complete. A Student can belong to one or more Businesses. A Student can belong to one more Admins.

**Properties**
- Name (String)
- Email (String)
- Code (Generated String)
- Courses (Array)
- Course progress
- Businesses (Array)
- Admins (Array)

**Comment by simon-lang** [comment]
I think we can omit the Student:Admin relationship. It will be inferred via Business.
